// GENERATED by `pnpm gen:town` from towns/*/town.yaml — edit the manifests, never this file.
import type { TownManifest } from './types';

export const TOWNS: Readonly<Record<string, TownManifest>> = {
  "base-sepolia": {
    "town": "base-sepolia",
    "status": "demo",
    "chain": {
      "id": 84532,
      "generation": "1",
      "rpc": "https://sepolia.base.org",
      "deployment": "base-sepolia"
    },
    "estates": [
      {
        "id": "impact",
        "repo": "agentictrustlabs/ap-demos",
        "home": "https://www.impact-agent.me",
        "edge": "https://edge.impact-agent.io",
        "a2a": "https://a2a.impact-agent.io",
        "nameRoots": [
          "impact",
          "agent"
        ]
      }
    ],
    "services": [
      {
        "id": "registry",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/registry",
        "worker": "demo-discovery-a2a",
        "hosts": [],
        "description": "The demo town's registry (default env of apps/registry)."
      },
      {
        "id": "discovery-mcp",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/discovery-mcp",
        "worker": "demo-discovery-mcp",
        "hosts": [],
        "description": "The demo town's graph reader."
      },
      {
        "id": "discovery-indexer",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/discovery-indexer",
        "worker": "demo-discovery-indexer",
        "hosts": [],
        "description": "The demo town's graph writer."
      }
    ]
  },
  "faithchain": {
    "town": "faithchain",
    "status": "live",
    "chain": {
      "id": 34348,
      "generation": "1",
      "rpc": "https://rpc.faithnet.io",
      "deployment": "faithchain",
      "coin": {
        "address": "0xa14E4a9447607c1233DcE34dB6Ead47C094f6141",
        "symbol": "SHQ",
        "decimals": 6
      }
    },
    "estates": [
      {
        "id": "faithnet",
        "repo": "agentictrustlabs/ap-home",
        "home": "https://www.faithnet.me",
        "edge": "https://edge.faithnet.io",
        "a2a": "https://a2a.faithnet.io",
        "agentZone": "faithnet.ai",
        "lanes": {
          "edge.faithnet.io": "demo-edge-faithnet",
          "demo-edge-faithnet.richardpedersen3.workers.dev": "demo-edge-faithnet",
          "*.faithnet.ai": "demo-a2a-faithnet"
        },
        "nameRoots": [
          "me",
          "org",
          "team",
          "svc",
          "workspace",
          "treasury",
          "registry",
          "church",
          "circle",
          "impact"
        ],
        "kms": {
          "tenant": "faithnet"
        }
      }
    ],
    "services": [
      {
        "id": "registry",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/registry",
        "worker": "demo-discovery-a2a-faithnet",
        "agentName": "discovery.registry",
        "hosts": [
          "discovery-a2a.faithnet.io"
        ],
        "probe": "https://discovery-a2a.faithnet.io/health",
        "card": "https://discovery-a2a.faithnet.io/.well-known/agent-card.json",
        "description": "The town's registry — the discovery.registry agent, its ARD document, ACP registry and search."
      },
      {
        "id": "discovery-mcp",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/discovery-mcp",
        "worker": "demo-discovery-mcp-faithnet",
        "hosts": [],
        "description": "Reads the public graph and the retrieval index for the registry. Reachable only by service binding."
      },
      {
        "id": "discovery-indexer",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/discovery-indexer",
        "worker": "demo-discovery-indexer-faithnet",
        "hosts": [],
        "description": "The only writer of the public graph and the retrieval index; crawls every estate's name roots."
      },
      {
        "id": "discovery-connector",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/discovery-connector",
        "worker": "demo-discovery-connector-faithnet",
        "hosts": [
          "discovery-connector.faithnet.io"
        ],
        "probe": "https://discovery-connector.faithnet.io/health",
        "description": "Public read-only MCP for external assistants, over the registry's search."
      },
      {
        "id": "discovery-web",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/discovery-web",
        "worker": "demo-discovery-web-faithnet",
        "hosts": [
          "discovery.faithnet.io"
        ],
        "probe": "https://discovery.faithnet.io/",
        "description": "The explorer's old host — the registry's documents at their well-known paths, and a redirect to the portal's Find."
      },
      {
        "id": "town-agent",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/town-agent",
        "worker": "faithchain-town-agent",
        "hosts": [
          "town.faithnet.io"
        ],
        "probe": "https://town.faithnet.io/api/health",
        "card": "https://town.faithnet.io/.well-known/agent-card.json",
        "description": "The town's own agent — what this town offers and whether each service is up. Lists; never grants."
      },
      {
        "id": "naming",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/naming",
        "worker": "faithchain-naming",
        "hosts": [
          "names.faithnet.io"
        ],
        "probe": "https://names.faithnet.io/api/health",
        "description": "The town's naming service — every name on the chain, what it points at, and who can change it. It reads; an owner's Home writes."
      },
      {
        "id": "chain-gateway",
        "kind": "commons",
        "repo": "ap-town",
        "app": "apps/chain-gateway",
        "worker": "faithchain-rpc-gateway",
        "hosts": [
          "rpc.faithnet.io"
        ],
        "description": "Chain access — per-app tokens, method allow-list, rate limits — in front of the faithchain node."
      },
      {
        "id": "skills",
        "kind": "commons",
        "repo": "agentictrustlabs/skills",
        "hosts": [
          "skills.faithnet.io"
        ],
        "probe": "https://skills.faithnet.io/",
        "description": "The skills registry — SKILL.md contracts and playbooks, pinned by digest."
      },
      {
        "id": "kms",
        "kind": "commons",
        "repo": "agentictrustlabs/faithkms",
        "hosts": [
          "akcs-pilot.faithnet.io"
        ],
        "probe": "https://akcs-pilot.faithnet.io/healthz",
        "description": "Key custody (AKCS) — a tenant per estate; keys are delegates, never identities."
      },
      {
        "id": "gamenight",
        "kind": "application",
        "repo": "agentictrustlabs/pokernight",
        "hosts": [
          "gamenight.faithnet.io",
          "games.faithnet.io",
          "agents.faithnet.io"
        ],
        "probe": "https://gamenight.faithnet.io/",
        "estates": [
          "faithnet"
        ],
        "description": "Game Night — people and agents at the same tables, including Field Operations."
      }
    ]
  }
};
